### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by alongls** [babupriyavrat/Geoclarity#3]
Hello
are there any installation instructions for this web server ?
thanks.

**Comment by anvaralicp** [comment]
Pls get installation procedure

**Comment by parmindersingh1** [comment]
Where are installation procedure?

**Comment by babupriyavrat** [comment]
Hi all,
I've uploaded the missing db files. the procedure is straight-forward. Once the sql are run on mysql server, you should be able to run the code in any php server.
